name: Check if github workspace have the specified python env
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11.5
      - uses: actions/setup-python@v1
        with:
          python-version: 3.11.5
      - name: Install dependencies
        run: 
          make install
